#
# Instalación general de software para Ubuntu y Fedora 34
#


- name: Gestiona aplicaciones en flatpak
  include_role:
    name: flatpaks
  tags:
    - slow
    - flatpak

- name: Gestiona aplicaciones en snap
  include_role:
    name: snaps
  tags:
    - slow
    - snap

- name: Gestiona paquetes en Ubuntu 24.04
  include_role:
    name: paquetes-ubuntu-2404
  when: ansible_distribution_version == "24.04"

- name: Gestiona paquetes en Ubuntu 26.04
  include_role:
    name: paquetes-ubuntu-2604
  when: ansible_distribution_version == "26.04"
