---
- hosts: aif
  user: root
  strategy: free

  vars:
    # He tenido que quitar los grupos sambashare,ubridge
    # Añado tty para que puedan utilizar minicom con un cable
    grupos: adm,cdrom,dialout,kvm,libvirt,lpadmin,lxd,plugdev,tty,vboxusers

  roles:
    - delete-users
    - lock-sshd
    - swappiness-0
    - role: vasilisa
      vars:
        sirin: "http://192.168.14.18:8080/register/aif-u2404.yml"
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
        base_hostname: "aif"
    - timesyncd-ntp
    - ubuntu-desktop-minimal
    - software
    - gnome-dconf-2404
    - wireshark
    - kvm
    - lxd-dir
    - glpi-agent
    - convidat
    - apagado-1455
    - apagado-2130

  tasks:
    # Usuarios
    - include_tasks: users/aig/alumnos/ga1a.yml
    - include_tasks: users/aig/alumnos/ga1b.yml
    - include_tasks: users/aig/alumnos/ga2.yml
    - include_tasks: users/aig/alumnos/af1.yml
    - include_tasks: users/aig/alumnos/af2.yml
    - include_tasks: users/aig/docent.yml
      when: ansible_default_ipv4.address == "192.168.14.100"
    - include_tasks: users/aig/docent.yml
      when: ansible_default_ipv4.address == "192.168.14.150"
    - include_tasks: users/informatica/pille.yml
      when: ansible_default_ipv4.address == "192.168.14.100"
    - include_tasks: users/informatica/pille.yml
      when: ansible_default_ipv4.address == "192.168.14.150"
