---
- hosts: chomsky
  user: root
  strategy: free

  vars:
    # He tenido que quitar los grupos sambashare,ubridge
    # Añado tty para que puedan utilizar minicom con un cable
    grupos: adm,cdrom,dialout,kvm,libvirt,lpadmin,lxd,plugdev,tty,vboxusers

  roles:
    - delete-users
    - lock-sshd
    - swappiness-0
    - role: vasilisa
      vars:
        sirin: "http://192.168.23.18:8080/register/chomsky-u2404.yml"
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
        base_hostname: "chomsky"
    - timesyncd-ntp
    - ubuntu-desktop-minimal
    - software
    - gnome-dconf-2404
    - wireshark
    - kvm
    - lxd-dir
    - glpi-agent
    - convidat
    - apagado-1455
    - apagado-2130

  tasks:
    # Usuarios
    #- include_tasks: users/informatica/alumnos/smx2a.yml
    #- include_tasks: users/informatica/alumnos/asix2a.yml
    - include_tasks: users/informatica/alumnos/dam2a.yml
    #- include_tasks: users/informatica/adriamt.yml
    #  when: ansible_default_ipv4.address == "192.168.23.100"
    #- include_tasks: users/informatica/imart53.yml
    #  when: ansible_default_ipv4.address == "192.168.23.100"
    #- include_tasks: users/informatica/jmimo.yml
    #  when: ansible_default_ipv4.address == "192.168.23.100"
    #- include_tasks: users/informatica/llorent4.yml
    #  when: ansible_default_ipv4.address == "192.168.23.100"
    #- include_tasks: users/informatica/luis.yml
    #  when: ansible_default_ipv4.address == "192.168.23.100"

    - name: Borrado de usuarios antiguos
      user:
              name: "{{ item }}"
              state: absent
              remove: yes
      with_items:
              - smx2d

