---
- hosts: init_portatils_alumnes_u2404
  user: root
  strategy: free

  vars:
    grupos: adm,cdrom,dialout,lpadmin,plugdev

  roles:
    - delete-users
    - lock-sshd
    - swappiness-0

    - role: vasilisa
      vars:
        sirin: "http://10.0.0.2:8000/launcher/?label=portatils-docents-u2204.yml"

    - activate-unattended-upgrades

    - role: cambia-hostname
      vars:
        base_hostname: "docent"
      
    - glpi-agent
      
    - flush-handlers

  tasks:
    - name: Instala wireguard-tools
      apt:
        name: wireguard-tools
        state: present

    - include_tasks: "vpn/{{ vpn }}.yml"

    - name: Activa la VPN wg0 (enable y start)
      systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Reboot
      reboot:
