
- name: Test sobre /opt/wireshark
  # Se utiliza /opt/wireshark como flag para indicar que wireshark está
  # debidamente instalado. 
  stat:
    path: /opt/wireshark
  register: archivo

- name: Wireshark let non root to capture traffic
  # Before installing any package, this only sets the preference for the question
  #
  # https://stackoverflow.com/questions/64686729/dpkg-reconfigure-openssh-server-in-ansible-playbook
  debconf:
    name='wireshark-common'
    question='wireshark-common/install-setuid'
    vtype='boolean'
    value='true'
  become: yes
  when: not archivo.stat.exists
  register: reconfigure_changed

- name: Crea el grupo wireshark
  group:
    name: wireshark
    state: present
    system: yes

- name: Instala Wireshark
  apt:
    pkg:
    - wireshark
  when: not archivo.stat.exists

- name: Make debconf changes active
  ansible.builtin.command:
    cmd: "dpkg-reconfigure wireshark-common"
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: reconfigure_changed.changed
  # Comentado porque quiero que lo haga en todos los equipos
  # luego debe hacer sólo cuando se haya reconfigurado.

- name: Crea /opt/wireshark para indicar que wireshark está хорошо
  file:
    path: /opt/wireshark
    state: touch
  when: not archivo.stat.exists
