
- name: Test sobre /opt/wireshark
  # Se utiliza /opt/wireshark como flag para indicar que wireshark está
  # debidamente instalado. 
  stat:
    path: /opt/wireshark
  register: archivo

- name: Wireshark let non root to capture traffic
  # Before installing any package, this only sets the preference for the question
  debconf:
    name='wireshark-common'
    question='wireshark-common/install-setuid'
    vtype='boolean'
    value='true'
  become: yes
  when: not archivo.stat.exists
#  notify:
#    - desinstala wireshark-common
#    - instala wireshark-common

- name: Crea el grupo wireshark
  group:
    name: wireshark
    state: present
    system: yes

- name: Desinstala Wireshark
  apt:
    state: absent
    pkg:
    - wireshark
  when: not archivo.stat.exists

- name: Instala Wireshark
  apt:
    pkg:
    - wireshark
  when: not archivo.stat.exists

- name: Crea /opt/wireshark para indicar que wireshark está хорошо
  file:
    path: /opt/wireshark
    state: touch
  when: not archivo.stat.exists
