- name: Instala lxd
  snap:
        name: lxd
  ignore_errors: yes

- name: copy lxd-preseed
  copy:
    src: files/lxd-preseed.yml
    dest: /root/lxd-preseed.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  register: lxd

- name: config lxd
  shell: cat /root/lxd-preseed.yml | /snap/bin/lxd init --preseed
  when: lxd.changed
