- name: Bloquea la autenticación con password en /etc/ssh/sshd_config
  replace:
    dest: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication yes'
    replace: 'PasswordAuthentication no'
  register: sshd_config

- name: restart ssh
  service:
    name: ssh
    state: restarted
  when: sshd_config.changed
