flatpaks_instalar:
  - org.ardour.Ardour
      - cc.arduino.arduinoide
      - org.audacityteam.Audacity
      - org.blender.Blender
      - com.brave.Browser
      - org.chromium.Chromium
      - com.visualstudio.code-oss
      - org.darktable.Darktable
      - io.dbeaver.DBeaverCommunity
      - org.kde.digikam
      - com.diy_fever.DIYLayoutCreator
      - org.filezillaproject.Filezilla
      - org.freecad.FreeCAD
      - org.fritzing.Fritzing
      - org.gaphor.Gaphor
      - org.geogebra.GeoGebra
      - org.gimp.GIMP
      - org.godotengine.Godot
      - org.inkscape.Inkscape
      - net.sourceforge.Klavaro
      - io.lmms.LMMS
      - org.kde.kbruch
      - org.kde.kcalc
      - org.kde.kdenlive
      - org.kde.kig
      - org.kde.ktouch
      - org.kicad.KiCad
      - org.kde.krita
      - org.libreoffice.LibreOffice
      - org.librepcb.LibrePCB
      - org.gnome.Maps
      - org.musescore.MuseScore
      - org.openshot.OpenShot
      - com.github.alexhuntley.Plots
      - com.obsproject.Studio
      - com.github.jeromerobert.pdfarranger
      - eu.scarpetta.PDFMixTool
      - com.github.junrrein.PDFSlicer
      - io.github.Qalculate
      - org.remmina.Remmina
      - com.rustdesk.RustDesk
      - edu.mit.Scratch
      - org.gnome.World.Secrets
      - org.gnome.SoundRecorder
      - com.sweethome3d.Sweethome3d
      - org.shotcut.Shotcut
      - com.transmissionbt.Transmission
      - ar.com.tuxguitar.TuxGuitar
      - org.kde.umbrello
      - org.videolan.VLC
      - dev.zed.Zed

flatpaks_retirar:
    - org.kde.kalzium
    - org.octave.Octave
    - org.openscad.OpenSCAD
    - com.prusa3d.PrusaSlicer
