flatpaks_instalar:
  - cc.arduino.IDE2
  - org.audacityteam.Audacity
  - org.blender.Blender
  - com.brave.Browser
  - org.chromium.Chromium
  - io.dbeaver.DBeaverCommunity
  - com.diy_fever.DIYLayoutCreator

  - org.freecad.FreeCAD
  - org.gaphor.Gaphor
  - org.gimp.GIMP
  - org.godotengine.Godot
  - org.inkscape.Inkscape
  - net.sourceforge.Klavaro
  - org.kde.kbruch
  - org.kde.kcalc
  - org.kde.kdenlive
  - org.kde.kig
  - org.kde.ktouch
  - org.kicad.KiCad
  - org.kde.krita
  - org.libreoffice.LibreOffice
  - org.librepcb.LibrePCB
  - org.gnome.Maps
  - org.musescore.MuseScore
  - com.obsproject.Studio
  - com.github.jeromerobert.pdfarranger
  - io.github.Qalculate
  - org.remmina.Remmina
  - org.gnome.World.Secrets
  - org.gnome.SoundRecorder
  - com.sweethome3d.Sweethome3d
  - org.shotcut.Shotcut
  - com.transmissionbt.Transmission
  - ar.com.tuxguitar.TuxGuitar
  - org.kde.umbrello
  - org.videolan.VLC
  - com.vscodium.codium
  - dev.zed.Zed

flatpaks_retirar:
  - org.ardour.Ardour
  - cc.arduino.arduinoide
  - org.darktable.Darktable
  - org.kde.digikam
  - org.filezillaproject.Filezilla
  - org.fritzing.Fritzing
  - org.geogebra.GeoGebra
  - org.kde.kalzium
  - io.lmms.LMMS
  - org.octave.Octave
  - org.openscad.OpenSCAD
  - org.openshot.OpenShot
  - eu.scarpetta.PDFMixTool
  - com.github.junrrein.PDFSlicer
  - com.rustdesk.RustDesk
  - edu.mit.Scratch
  - com.visualstudio.code-oss
  - com.github.alexhuntley.Plots
  - com.prusa3d.PrusaSlicer
