#
# Instalación de snaps
#

- name: Instala snaps
  snap:
    name: "{{ item }}"
  loop:
    - beekeeper-studio
    - modelio
  register: resultado
  until: resultado is succeeded
  retries: 3
  delay: 30

- name: Instala snaps classic
  snap:
    name: "{{ item }}"
    classic: yes
  loop:
    - go
    - intellij-idea-community
  register: resultado
  until: resultado is succeeded
  retries: 3
  delay: 30
