# Instalación de paquetes Flatpak
#
#

- name: Instala flatpak
  apt:
    pkg: flatpak
    state: present
    update_cache: yes

- name: Instala aplicaciones flatpak desde flathub
    flatpak:
      name: "https://dl.flathub.org/repo/appstream/{{ item }}.flatpakref"
      state: present
    loop: "{{ flatpaks_instalar }}"
    loop_control:
      label: "{{ item }}"
    register: resultado
    until: resultado is succeeded
    retries: 3
    delay: 30

- name: Desinstala aplicaciones flatpak retiradas
  flatpak:
    name: "{{ item }}"
    state: absent
  loop: "{{ flatpaks_retirar }}"
