#
# Gestiona los paquetes en Ubuntu
#

# Instalación de paquetes
- name: Instalación de paquetes que están en los repos de Ubuntu
  apt:
    update_cache: yes
    pkg:
    - basex
    - dia
    - dia-rib-network
    - dia-shapes
    - dia2code
    - dialog
    - docutils-doc
    - git
    - gnome-boxes
    - htop
    - httpie
    - ipcalc
    - jq
    - librecad
    - lldpd
    - lyx
    - net-tools
    - ncdu
    - openjdk-21-jdk
    - pdftk
    - planner
    - podman
    - postgresql-client
    - prometheus-node-exporter
    - pylint
    - python3-docutils
    - python3-easygui
    - python3-pip
    - python3-venv
    - relational
    - rst2pdf
    - ripgrep
    - ruby
    - ruby-bundler
    - sshfs
    - texlive-lang-spanish
    - tree
    - tshark
    - ttf-mscorefonts-installer
    - unrar
    - vim
    - virt-top
    - virt-viewer
    - virtualbox
    - virtualenv
    - vpcs
    - xorriso

#- name: Instala drivers de nvidia en Lenovo ThinkCentre M90t Gen 3
#  apt:
#    pkg:
#      # Atención: Instalar nvidia-driver-525-open rompe el arranque.
#      - nvidia-driver-525
#  when:
#    # Utilizamos las dos propiedades para asegurarnos de que se trata de los equipos con nvidia
#    - ansible_product_name == "11TUS02Q00"
#    - ansible_product_version == "ThinkCentre M90t Gen 3" 

- name: Elimina paquetes innecesarios con apt autoremove
  apt:
    autoremove: yes

# Desactiva el collector de systemd porque tiene una cardinalidad muy alta
# https://www.robustperception.io/dropping-metrics-at-scrape-time-with-prometheus
- name: Aplica --no-collector.systemd en /etc/default/prometheus-node-exporter
  replace:
    dest: /etc/default/prometheus-node-exporter
    regexp: '^ARGS=""'
    replace: 'ARGS="--no-collector.systemd"'
